//
// QuestionAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class QuestionAPI: APIBase {
    /**
     Send question by email to Pro Athlete
     
     - parameter questionStoreData: (body) Question data 
     - parameter limit: (query) Page size for paginated data (optional)
     - parameter page: (query) Page number for paginated data, 1-based (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func questionStore(questionStoreData: QuestionStoreData, limit: Int32? = nil, page: Int32? = nil, completion: @escaping ((_ data: SuccessConfirmation?,_ error: Error?) -> Void)) {
        questionStoreWithRequestBuilder(questionStoreData: questionStoreData, limit: limit, page: page).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Send question by email to Pro Athlete
     - POST /questions
     - examples: [{contentType=application/json, example={
  "message" : "aeiou"
}}]
     
     - parameter questionStoreData: (body) Question data 
     - parameter limit: (query) Page size for paginated data (optional)
     - parameter page: (query) Page number for paginated data, 1-based (optional)

     - returns: RequestBuilder<SuccessConfirmation> 
     */
    open class func questionStoreWithRequestBuilder(questionStoreData: QuestionStoreData, limit: Int32? = nil, page: Int32? = nil) -> RequestBuilder<SuccessConfirmation> {
        let path = "/questions"
        let URLString = BPMClientAPI.basePath + path
        let parameters = questionStoreData.encodeToJSON() as? [String:AnyObject]
 
        //let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<SuccessConfirmation>.Type = BPMClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: false)
    }

}
