//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class UserAPI: APIBase {
    /**
     Register new User
     
     - parameter userStoreData: (body) User Data 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userStore(userStoreData: UserStoreData, completion: @escaping ((_ data: SuccessConfirmation?,_ error: Error?) -> Void)) {
        userStoreWithRequestBuilder(userStoreData: userStoreData).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Register new User
     - POST /users
     - examples: [{contentType=application/json, example={
  "message" : "aeiou"
}}]
     
     - parameter userStoreData: (body) User Data 

     - returns: RequestBuilder<SuccessConfirmation> 
     */
    open class func userStoreWithRequestBuilder(userStoreData: UserStoreData) -> RequestBuilder<SuccessConfirmation> {
        let path = "/users"
        let URLString = BPMClientAPI.basePath + path
        let parameters = userStoreData.encodeToJSON() as? [String:AnyObject]
 
        //let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<SuccessConfirmation>.Type = BPMClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

}
