//
// CategoryListData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Category */
open class CategoryListData: JSONEncodable {
    /** Category ID */
    public var id: Int32?
    /** Category name */
    public var category: String?
    /** Category ID */
    public var parentId: Int32?
    /** Post count */
    public var postCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["category"] = self.category
        nillableDictionary["parent_id"] = self.parentId?.encodeToJSON()
        nillableDictionary["post_count"] = self.postCount?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
