//
// CursorPaginationInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Pagination info for lists of records with cursor-based pagination */
open class CursorPaginationInfo: JSONEncodable {
    /** Total number of records in currently in data set */
    public var total: Int32?
    /** Number of records in currently returned list */
    public var count: Int32?
    /** Current cursor value */
    public var current: String?
    /** Cursor value for previous page (not currently supported) */
    public var prev: String?
    /** Cursor value for the next page */
    public var next: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["current"] = self.current
        nillableDictionary["prev"] = self.prev
        nillableDictionary["next"] = self.next
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
