//
// ErrorDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ErrorDetails: JSONEncodable {
    /** Error message, that should be shown to user */
    public var message: String?
    /** Duplicates HTTP status code */
    public var statusCode: Int32?
    /** List of validation errors */
    public var errors: [ErrorDetailsErrors]?
    public var debug: ErrorDetailsDebug?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["message"] = self.message
        nillableDictionary["status_code"] = self.statusCode?.encodeToJSON()
        nillableDictionary["errors"] = self.errors?.encodeToJSON()
        nillableDictionary["debug"] = self.debug?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
