//
// ErrorDetailsDebug.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Information for debugging */
open class ErrorDetailsDebug: JSONEncodable {
    /** Line of code */
    public var line: Int32?
    /** File where error happened */
    public var file: String?
    /** PHP class name */
    public var _class: String?
    /** Trace */
    public var trace: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["line"] = self.line?.encodeToJSON()
        nillableDictionary["file"] = self.file
        nillableDictionary["class"] = self._class
        nillableDictionary["trace"] = self.trace?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
