//
// PaginationInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Pagination info for paginated lists of records */
open class PaginationInfo: JSONEncodable {
    /** Total number of records in data set */
    public var total: Int32?
    /** Number of records in currently returned list */
    public var count: Int32?
    /** Number of records per page */
    public var perPage: Int32?
    /** Current page number, 1-based */
    public var currentPage: Int32?
    /** Total number of pages available */
    public var totalPages: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["total"] = self.total?.encodeToJSON()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["per_page"] = self.perPage?.encodeToJSON()
        nillableDictionary["current_page"] = self.currentPage?.encodeToJSON()
        nillableDictionary["total_pages"] = self.totalPages?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
