//
// PostListPhotos.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model Photo */
open class PostListPhotos: JSONEncodable {
    /** Internal ID */
    public var id: Int32?
    /** Internal Post ID who own this photo */
    public var postId: Int32?
    /** File name */
    public var file: String?
    /** File original client name */
    public var fileOriginal: String?
    /** Location of photo file - download URL */
    public var fileUrl: String?
    /** Photo file size */
    public var fileSize: Int32?
    /** File name */
    public var fileThumbnail: String?
    /** Location of photo file - download URL */
    public var fileThumbnailUrl: String?
    /** Photo file size */
    public var fileThumbnailSize: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["post_id"] = self.postId?.encodeToJSON()
        nillableDictionary["file"] = self.file
        nillableDictionary["file_original"] = self.fileOriginal
        nillableDictionary["file_url"] = self.fileUrl
        nillableDictionary["file_size"] = self.fileSize?.encodeToJSON()
        nillableDictionary["file_thumbnail"] = self.fileThumbnail
        nillableDictionary["file_thumbnail_url"] = self.fileThumbnailUrl
        nillableDictionary["file_thumbnail_size"] = self.fileThumbnailSize?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
