//
// PostListData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Post model. Can include &#39;photos&#39; */
open class PostListData: JSONEncodable {
    /** Internal ID */
    public var id: Int32?
    /** Post Description */
    public var description: String?
    /** Internal Category ID */
    public var categoryId: Int32?
    /** Timestamp when post was created, ISO 8601 */
    public var createdAt: Date?
    /** Photos of post. Not required */
    public var photos: [PostListPhotos]?
    public var user: User?
    /** Number of post&#39;s vote */
    public var votes: Int32?
    /** indicate whether the current user voted this post or not */
    public var voted: Bool?
    /** indicate whehter the post is expired (cannot vote) */
    public var expired: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["category_id"] = self.categoryId?.encodeToJSON()
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["photos"] = self.photos?.encodeToJSON()
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["votes"] = self.votes?.encodeToJSON()
        nillableDictionary["voted"] = self.voted
        nillableDictionary["expired"] = self.expired
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
