//
// UpdateUserPasswordBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UpdateUserPasswordBody: JSONEncodable {
    /** User password */
    public var password: String?
    /** User password */
    public var newPassword: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["password"] = self.password
        nillableDictionary["new_password"] = self.newPassword
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
