//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model User profile */
open class User: JSONEncodable {
    /** Internal ID */
    public var id: Int32?
    /** User first name, visible to other users */
    public var firstName: String?
    /** User last name, visible to other users */
    public var lastName: String?
    /** Registered user email */
    public var email: String?
    /** If user is admin - has full access to backend management */
    public var isAdmin: Bool?
    /** 1 - male, 0 - female */
    public var gender: Int32?
    /** User city */
    public var city: String?
    /** User state */
    public var state: String?
    /** User zip code */
    public var zipCode: String?
    /** Location of avatar image - download URL */
    public var avatarFileUrl: String?
    /** Timestamp when user was created, ISO 8601 */
    public var createdAt: Date?
    /** Number of posts which the user voted */
    public var voteCount: Int32?
    /** Limit of posts which the user can make */
    public var voteLimit: Int32?
    /** Limit of free posts which the user can make per month */
    public var freePostLimitPerMonth: Int32?
    /** Number of free posts which the user created */
    public var freePostCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["first_name"] = self.firstName
        nillableDictionary["last_name"] = self.lastName
        nillableDictionary["email"] = self.email
        nillableDictionary["is_admin"] = self.isAdmin
        nillableDictionary["gender"] = self.gender?.encodeToJSON()
        nillableDictionary["city"] = self.city
        nillableDictionary["state"] = self.state
        nillableDictionary["zip_code"] = self.zipCode
        nillableDictionary["avatar_file_url"] = self.avatarFileUrl
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["vote_count"] = self.voteCount?.encodeToJSON()
        nillableDictionary["vote_limit"] = self.voteLimit?.encodeToJSON()
        nillableDictionary["free_post_limit_per_month"] = self.freePostLimitPerMonth?.encodeToJSON()
        nillableDictionary["free_post_count"] = self.freePostCount?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
